### ISSUE TITLE
Sepsis dataset features meaning and origin

### ISSUE THREAD

**Issue by davidechicco** [prise6/aVirtualTwins#4]
Dear Francois Vielle,

My name is Davide Chicco and I am a scientific associate researcher at the Peter Munk Cardiac Centre. I work on machine learning applied to health care, and I am especially
interested in sepsis prediction in patients.

I just discovered your aVirtualTwins project, and I downloaded the code and the dataset. The dataset looks very interesting to me, and I would like to know more about it.

Some questions:

1)) I just took a look at the features: "survival" "THERAPY"
"PRAPACHE" "AGE"      "BLGCS"    "ORGANNUM"  "BLIL6"    "BLLPLAT"
"BLLBILI"  "BLLCREAT" "TIMFIRST" "BLADL"  "blSOFA".
What is the meaning of these feature names?
Where can I find more information about them?

I found the description of these features in your thesis in French.

> survival: 1 pour la survie au bout de 28 jours, 0 sinon
> THERAPY: 1 pour le traitement actif, 0 pour le traitement de contrôle
> TIMFIRST: Temps entre la prise de traitement et la défaillance du premier organe
> AGE: Age du patient en années
> BLLPLAT: Les plaquettes à baseline
> blSOFA: Somme du sofa à baseline (score)
> BLLCREAT: Créatinine à baseline
> ORGANNUM: Nombre d'organes en défaillance à baseline
> PRAPACHE: Score Pre-infusion Apache II
> BLGCS: Echelle de Glasgow (état de conscience) à baseline
> BLIL6: Concentration du serum IL-6 à baseline
> BLADL: score Activity of daily
> BLLBILI: Bilirubine à baseline

Can you please translate them into English please?

2)) What is the origin of this dataset? 
Did you collect it from an hospital? Was it an online resource?

3)) Did you publish any scientific paper about this project?
If yes, can you please share it here?

Merci beaucoup, au revoir

-- Davide

**Comment by prise6** [comment]
Hi,
Thank you for your interest.

Concerning sepsis dataset, references in english are in the vignette package or in the [wiki](https://github.com/prise6/aVirtualTwins/wiki): introduction + sepsis dataset. This dataset was taken from another project called SIDES. I guess you'll find better references about dataset's origins. (I can't remember exactly the details, maybe it was simulated from real data).
Variables details are also in the wiki.

Concerning virtual twins methods : as far as i know, the virtual twins paper, my french report and maybe [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6015941/) gives details on it.

Hope it helps :)

Bon courage!

**Comment by prise6** [comment]
I close this issue, feel free to re-open if needed.
